### ISSUE TITLE
Authentication: Create Authentication workflow 

### ISSUE THREAD

**Issue by Jhector10** [Stevens-ReCollect/ReCollect#11]
- [ ] Front End: Create the Front end design from the Figma Prototype 

- [ ] Back End: Create the Firebase Authentication feature (via Google)

- [ ] Full Stack: Connect the two to create the authentication sign in page

**Comment by Jhector10** [comment]
Do we want to add authentication through Google, or through email/password?

**Comment by LDomadia** [comment]
From #35: Users and their information should be added to Firebase when they "Sign Up" on ReCollect
