### ISSUE TITLE
Bug: Screen goes Black when deleting a Memory with no data in it

### ISSUE THREAD

**Issue by Jhector10** [Stevens-ReCollect/ReCollect#113]
![32d83eed13cf4939b1201416cb972d6e](https://user-images.githubusercontent.com/62861172/152044968-cec0f1d9-8262-4fdb-a4ae-0525c50ea963.jpeg)

**Comment by LDomadia** [comment]
Black screen is now fixed. What do we think about the snack bar (the Successfully deleted memory message). Is it too close to the bottom navbar? Should we make any changes to it?

<img src="https://user-images.githubusercontent.com/62802533/152194923-0fc8aa7d-7505-430e-83d4-b145df6e4b81.png" width=200px>
